# Generated by Django 3.2.7 on 2021-10-14 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentaccount',
            old_name='constituencies',
            new_name='constituency',
        ),
        migrations.RenameField(
            model_name='studentaccount',
            old_name='dateOfBirth',
            new_name='d_o_b',
        ),
        migrations.RenameField(
            model_name='studentaccount',
            old_name='emailAddress',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='studentaccount',
            old_name='firstName',
            new_name='id_no',
        ),
        migrations.RenameField(
            model_name='studentaccount',
            old_name='idNumber',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='studentaccount',
            old_name='middleName',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='studentaccount',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='studentaccount',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='studentaccount',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='studentaccount',
            name='town',
        ),
    ]
